esphome:
  name: pompa_mester
  on_boot:
    priority: -100
    then:
      light.turn_on:
         id: status_led

esp8266:
  board: esp8285

logger:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

api:

web_server:
  port: 80

ota:
  safe_mode: True
  password: !secret ota_password

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode:
        input: true
        pullup: true
      inverted: true
    id: button_1
    on_press:
      then:
        - switch.toggle: ontozes_pompa
  - platform: gpio
    pin:
      number: GPIO9
      mode:
        input: true
        pullup: true
      inverted: true
    id: button_2
    on_press:
      then:
        - switch.toggle: ontozes_vezetek
  
  - platform: gpio
    pin:
      number: GPIO10
      mode:
        input: true
        pullup: true
      inverted: true
    id: button_3
    on_press:
      then:
        - switch.toggle: urito_pompa
  
  - platform: gpio
    pin:
      number: GPIO14
      mode:
        input: true
        pullup: true
      inverted: true
    id: button_4
    on_press:
      then:
        - switch.toggle: pince_ajto
  
  - platform: status
    name: "Pompa Mester Status"


switch:
  - platform: gpio
    pin: GPIO12
    id: ontozes_pompa
    interlock: 
       - ontozes_vezetek
  - platform: gpio
    pin: GPIO5
    id: ontozes_vezetek
    interlock: 
       - ontozes_pompa
  - platform: gpio
    name: "Urito Pompa"
    pin: GPIO4
    id: urito_pompa
  - platform: gpio
    name: "Pince Ajto"
    pin: GPIO15
    id: pince_ajto
  - platform: template
    id: use_tank
    optimistic: true 
    icon: "mdi:water-pump"
    name: "Van viz a tartalyban?"
  - platform: template
    id: water_flow
    icon: "mdi:water-pump"
    name: "Viz inditasa"
    optimistic: true
    turn_on_action:
       then:  
          - if:
               condition:
                 - switch.is_on: use_tank
               then:
                 - switch.turn_on: ontozes_pompa
               else:
                 - switch.turn_on: ontozes_vezetek
          # This is a failsafe for how long the water will run for max
          - delay: 45 minutes
          - switch.turn_off: water_flow
    turn_off_action:
      - switch.turn_off: ontozes_vezetek   
      - switch.turn_off: ontozes_pompa 

output:
  # Register the blue LED as a dimmable output ....
  - platform: esp8266_pwm
    id: blue_led
    pin: GPIO13
    inverted: true

light:
  # ... and then make a light out of it.
  - platform: monochromatic
    output: blue_led
    id: status_led

sensor:
  - platform: wifi_signal
    name: "WiFi Signal Ontozo Mester"
    update_interval: 60s   
  - platform: dht
    pin: GPIO3
    temperature:
      name: "Pince Temperature"
    humidity:
      name: "Pince Humidity"
    model: AM2302
    update_interval: 60s   

