esphome:
  name: solar_heat
  platform: ESP32
  board: nodemcu-32s    
  on_boot:
    priority: -100
    then:
      - switch.turn_on: led_status


wifi:
  ssid: !secret wifi_ssid_mobile
  password: !secret wifi_password_mobile
  reboot_timeout: 0s  

logger:

web_server:
  port: 80

ota:
  safe_mode: True
  password: !secret ota_password

switch:
  - id: led_status
    platform: gpio
    pin: 
      number: GPIO27
    restore_mode: ALWAYS_OFF    
  - id: led_1
    platform: gpio
    pin: 
      number: GPIO14
    restore_mode: ALWAYS_OFF    
  - id: led_2
    platform: gpio
    pin: 
      number: GPIO12
    restore_mode: ALWAYS_OFF    
  - id: relay_1
    name: "Priza 1"
    platform: gpio
    pin: 
      number: GPIO26
    restore_mode: ALWAYS_OFF    
    on_turn_on:
      - switch.turn_on: led_1
    on_turn_off:
      - switch.turn_off: led_1
  - id: relay_2
    name: "Priza 2"
    platform: gpio
    pin: 
      number: GPIO25
    restore_mode: ALWAYS_OFF    
    on_turn_on:
      - switch.turn_on: led_2
    on_turn_off:
      - switch.turn_off: led_2

sensor:
  - platform: wifi_signal
    name: "WiFi"
    update_interval: 60s    

  - platform: ct_clamp
    sensor: adc_sensor
    name: "Termelt aram"
    update_interval: 10s
    sample_duration: 300ms
    filters:
      - calibrate_linear:
        - 0 -> 0
        - 0.40 -> 23.5
        - 0.27 -> 12.6
    on_value_range:
      - below: 10
        then:
           - switch.turn_off: relay_1
           - switch.turn_off: relay_2
      - above: 10
        below: 19
        then:
           - switch.turn_on: relay_1
           - switch.turn_off: relay_2
      - above: 19
        then:
           - switch.turn_on: relay_1
           - switch.turn_on: relay_2
  - platform: adc
    pin: GPIO34
      #attenuation: 11db 
    id: adc_sensor   

  - platform: dht
    pin: GPIO32
    model: AM2302
    temperature:
      name: "Homerseklet"
    humidity:
      name: "Nedvesseg"
    update_interval: 60s
