platform: thermostat
name: ${name}
sensor: ${sensor}
on_boot_restore_from: memory  
visual:
    min_temperature: 16
    max_temperature: 25
    temperature_step: 0.1
min_heating_off_time: 600s
min_heating_run_time: 600s
min_idle_time: 300s
heat_deadband: 0.2
heat_overrun: 0.0
default_preset: "Every Start Preset"
preset:
  - name: "Every Start Preset"
    default_target_temperature_low: 21
    mode: heat
  - name: "Rarely frequented"
    default_target_temperature_low: 21.5
    mode: heat
  - name: "Somewhat Frequented"
    default_target_temperature_low: 22.5
    mode: heat
  - name: "Sitting there a lot"
    default_target_temperature_low: 23.5
    mode: heat
  - name: "Sleep"
    default_target_temperature_low: 22
    mode: heat
heat_action:
   - switch.turn_on: ${relay}
idle_action:
   - switch.turn_off: ${relay}
