esphome:
  name: peter_mester
  platform: ESP8266
  board: esp12e

#web_server:
#  port: 80

wifi:
  fast_connect: true
  power_save_mode: none  
  output_power: 20db  
  ssid: !secret wifi_ssid
  password: !secret wifi_password

# Enable logging
logger:
  baud_rate: 0

# Enable Home Assistant API
api:

ota:
  safe_mode: True
  password: !secret ota_password

i2c:
  sda: GPIO1
  scl: GPIO3
  scan: true
  id: bus_a

ads1115:
  - address: 0x48

globals:
  - id: is_hot_water_circulation_on
    type: boolean
    restore_value: yes
    initial_value: "false" 

sensor:
  - platform: dht
    pin: GPIO2
    temperature:
      name: "Technical Room Temperature"
    humidity:
      name: "Technical Room Humidity"
    model: AM2302
    update_interval: 30s

  - platform: ads1115
    multiplexer: 'A0_GND'
    id: voltage_sensor_0
    gain: 6.144
    update_interval: 30s
  - platform: resistance
    sensor: voltage_sensor_0
    configuration: UPSTREAM
    resistor: 10kOhm
    reference_voltage: 5
    id: resistance_sensor_0
  - platform: ntc
    sensor: resistance_sensor_0
    name: "Hot Water Circuit Temp"
    id: hot_water_circuit_temp
    calibration:
       - 10.0kOhm -> 25°C
       - 4.76kOhm -> 38.8°C
       - 16.09kOhm -> 14.2°C
    filters:
      - median:
          window_size: 6
          send_every: 3
          send_first_at: 3
    on_value_range:
      - below: 25.0
        then:
          - switch.turn_off: relay8
      - above: 25.0
        below: 38.0
        then:
          - if:
              condition:
                 lambda: |-
                    return id(is_hot_water_circulation_on);
              then:               
                 - switch.turn_on: relay8
                 - delay: 180s
                 - switch.turn_off: relay8                
      - above: 41.0
        then:
          - switch.turn_off: relay8

  - platform: ads1115
    multiplexer: 'A1_GND'
    id: voltage_sensor_1
    gain: 6.144
    update_interval: 30s
  - platform: resistance
    sensor: voltage_sensor_1
    configuration: UPSTREAM
    resistor: 10kOhm
    reference_voltage: 5
    id: resistance_sensor_1
  - platform: ntc
    sensor: resistance_sensor_3
    name: "Hot Watter Mixing Temperature"
    id: heating_outgress_temp
    calibration:
       - 10.0kOhm -> 25°C
       - 5.62kOhm -> 38.1°C
       - 15.96kOhm -> 14.1°C
    filters:
      - sliding_window_moving_average:
          window_size: 6
          send_every: 2

  - platform: ads1115
    multiplexer: 'A2_GND'
    id: voltage_sensor_2
    gain: 6.144
    update_interval: 30s
  - platform: resistance
    sensor: voltage_sensor_2
    configuration: UPSTREAM
    resistor: 10kOhm
    reference_voltage: 5
    id: resistance_sensor_2
  - platform: ntc
    sensor: resistance_sensor_2
    name: "Hot Watter Upper Half Temperature"
    id: heating_ingress_temp
    calibration:
       - 10.0kOhm -> 25°C
       - 5.60kOhm -> 38.6°C
       - 15.92kOhm -> 14.1°C
    filters:
      - sliding_window_moving_average:
          window_size: 6
          send_every: 2
  
  - platform: template
    name: "Hot Water Delta Between top and middle"
    lambda: |-
        return id(heating_ingress_temp).state - id(water_reserve_temp).state;
    update_interval: 10s
    device_class: temperature
    unit_of_measurement: °C


  - platform: ads1115
    multiplexer: 'A3_GND'
    id: voltage_sensor_3
    gain: 6.144
    update_interval: 30s
  - platform: resistance
    sensor: voltage_sensor_3
    configuration: UPSTREAM
    resistor: 10kOhm
    reference_voltage: 5
    id: resistance_sensor_3
  - platform: ntc
    sensor: resistance_sensor_1
    name: "Hot water reserve"
    id: water_reserve_temp
    calibration:
       - 10.0kOhm -> 25°C
       - 5.76kOhm -> 37.9°C
       - 15.98kOhm -> 14.1°C
    filters:
      - sliding_window_moving_average:
          window_size: 6
          send_every: 2

  - platform: homeassistant
    id: iroda_current_temperature
    entity_id: sensor.iroda_levego_air_temperature
  - platform: homeassistant
    id: konyha_nappali_current_temperature
    entity_id: sensor.nappali_multisensor_air_temperature 
  - platform: homeassistant
    id: lanyok_current_temperature
    entity_id: sensor.nappali_air_temperature
  - platform: homeassistant
    id: halo_current_temperature
    entity_id: sensor.air_quality_sensor_air_temperature
  - platform: homeassistant
    id: jatszo_current_temperature
    entity_id: sensor.multisensor_nappali_air_temperature

# Four relay outputs, exposed as switches in Home Assistant
switch:
  - platform: gpio
    pin: GPIO16
    name: "Iroda Futes"
    id: relay1
  - platform: gpio
    pin: GPIO14
    name: "Konyha es Nappali Futes"
    id: relay2
  - platform: gpio
    pin: GPIO12
    name: "Lanyok Futes"
    id: relay3
  - platform: gpio
    pin: GPIO13
    name: "Halo Futes"
    id: relay4
  - platform: gpio
    pin: GPIO15
    name: "Jatszo Futes"
    id: relay5
  - platform: gpio
    pin: GPIO00
    name: Relay6
    id: relay6
  - platform: gpio
    pin: GPIO04
    name: Relay7
    id: relay7
  - platform: gpio
    pin: GPIO05
    name: "Hot Water Pump"
    id: relay8
  - platform: template
    id: "hot_water_circulation"
    name: "Hot Water Circulation"
    icon: "mdi:pump"
    lambda: |-
      return id(is_hot_water_circulation_on);
    turn_on_action:
      - lambda: |-
           id(is_hot_water_circulation_on) = true;
    turn_off_action:
      - lambda: |-
           id(is_hot_water_circulation_on) = false;
      - switch.turn_off: relay8

climate:
  - !include { file: 'climate.yml', vars: { name: "Iroda Melegites", sensor: "iroda_current_temperature", relay: "relay1" }}
  - !include { file: 'climate.yml', vars: { name: "Konyha es Nappali Melegites", sensor: "konyha_nappali_current_temperature", relay: "relay2" }}
  - !include { file: 'climate.yml', vars: { name: "Lanyok Melegites", sensor: "lanyok_current_temperature", relay: "relay3" }}
  - !include { file: 'climate.yml', vars: { name: "Halo Melegites", sensor: "halo_current_temperature", relay: "relay4" }}
  - !include { file: 'climate.yml', vars: { name: "Jatszo Melegites", sensor: "jatszo_current_temperature", relay: "relay5" }}
  - platform: thermostat
    name: Melegviz Hofok
    sensor: water_reserve_temp
    on_boot_restore_from: memory   
    visual:
      min_temperature: 40
      max_temperature: 60
      temperature_step: 2
    min_heating_off_time: 120s
    min_heating_run_time: 180s
    min_idle_time: 300s
    heat_deadband: 2
    heat_overrun: 7
    idle_action:
       - logger.log: "Hot water going idle"
    heat_action:  
       - logger.log: "Hot water heating"
