esphome:
  name: peter_mester
  platform: ESP8266
  board: esp12e

web_server:
  port: 80

wifi:
  fast_connect: true
  power_save_mode: none  
  output_power: 20db  
  ssid: !secret wifi_ssid
  password: !secret wifi_password

# Enable logging
logger:
  baud_rate: 0

# Enable Home Assistant API
api:

ota:
  safe_mode: True
  password: !secret ota_password

i2c:
  sda: GPIO1
  scl: GPIO3
  scan: true
  id: bus_a

ads1115:
  - address: 0x48

sensor:
  - platform: ads1115
    multiplexer: 'A0_GND'
    id: voltage_sensor_0
    gain: 6.144
    update_interval: 30s

  - platform: resistance
    sensor: voltage_sensor_0
    configuration: UPSTREAM
    resistor: 10kOhm
    reference_voltage: 5
    id: resistance_sensor_0

  - platform: ntc
    sensor: resistance_sensor_0
    name: "Temp 0"
    calibration:
       - 10.0kOhm -> 25°C
       - 24.97kOhm -> 5.3°C
       - 14.82kOhm -> 15.9°C

# Four relay outputs, exposed as switches in Home Assistant
switch:
  - platform: gpio
    pin: GPIO16
    name: Relay1
    id: relay1
  - platform: gpio
    pin: GPIO14
    name: Relay2
    id: relay2
  - platform: gpio
    pin: GPIO12
    name: Relay3
    id: relay3
  - platform: gpio
    pin: GPIO13
    name: Relay4
    id: relay4
  - platform: gpio
    pin: GPIO15
    name: Relay5
    id: relay5
  - platform: gpio
    pin: GPIO00
    name: Relay6
    id: relay6
  - platform: gpio
    pin: GPIO04
    name: Relay7
    id: relay7
  - platform: gpio
    pin: GPIO05
    name: Relay8
    id: relay8
