esphome:
  name: peter_mester
  platform: ESP8266
  board: esp12e

web_server:
  port: 80

wifi:
  fast_connect: true
  power_save_mode: none  
  output_power: 20db  
  ssid: !secret wifi_ssid
  password: !secret wifi_password

# Enable logging
logger:
  baud_rate: 0

# Enable Home Assistant API
api:

ota:
  safe_mode: True
  password: !secret ota_password

i2c:
  sda: GPIO1
  scl: GPIO3
  scan: true
  id: bus_a

ads1115:
  - address: 0x48

globals:
  - id: is_hot_water_circulation_on
    type: boolean
    restore_value: yes
    initial_value: "false" 

sensor:
  - platform: dht
    pin: GPIO2
    temperature:
      name: "Technical Room Temperature"
    humidity:
      name: "Technical Room Humidity"
    model: AM2302
    update_interval: 30s

  - platform: ads1115
    multiplexer: 'A0_GND'
    id: voltage_sensor_0
    gain: 6.144
    update_interval: 30s
  - platform: resistance
    sensor: voltage_sensor_0
    configuration: UPSTREAM
    resistor: 10kOhm
    reference_voltage: 5
    id: resistance_sensor_0
  - platform: ntc
    sensor: resistance_sensor_0
    name: "Hot Water Circuit Temp"
    id: hot_water_circuit_temp
    calibration:
       - 10.0kOhm -> 25°C
       - 4.76kOhm -> 38.8°C
       - 16.09kOhm -> 14.2°C
    filters:
      - sliding_window_moving_average:
          window_size: 6
          send_every: 2
    on_value_range:
      - below: 34.0
        then:
          - if:
              condition:
                 lambda: |-
                    return id(is_hot_water_circulation_on);
              then:               
                 - switch.turn_on: relay8
      - above: 39.0
        then:
          - switch.turn_off: relay8

  - platform: ads1115
    multiplexer: 'A1_GND'
    id: voltage_sensor_1
    gain: 6.144
    update_interval: 30s
  - platform: resistance
    sensor: voltage_sensor_1
    configuration: UPSTREAM
    resistor: 10kOhm
    reference_voltage: 5
    id: resistance_sensor_1
  - platform: ntc
    sensor: resistance_sensor_1
    name: "Heating Outgress Temp"
    id: heating_outgress_temp
    calibration:
       - 10.0kOhm -> 25°C
       - 5.62kOhm -> 38.1°C
       - 15.96kOhm -> 14.1°C
    filters:
      - sliding_window_moving_average:
          window_size: 6
          send_every: 2

  - platform: ads1115
    multiplexer: 'A2_GND'
    id: voltage_sensor_2
    gain: 6.144
    update_interval: 30s
  - platform: resistance
    sensor: voltage_sensor_2
    configuration: UPSTREAM
    resistor: 10kOhm
    reference_voltage: 5
    id: resistance_sensor_2
  - platform: ntc
    sensor: resistance_sensor_2
    name: "Heating Ingress"
    id: heating_ingress_temp
    calibration:
       - 10.0kOhm -> 25°C
       - 5.60kOhm -> 38.6°C
       - 15.92kOhm -> 14.1°C
    filters:
      - sliding_window_moving_average:
          window_size: 6
          send_every: 2

  - platform: ads1115
    multiplexer: 'A3_GND'
    id: voltage_sensor_3
    gain: 6.144
    update_interval: 30s
  - platform: resistance
    sensor: voltage_sensor_3
    configuration: UPSTREAM
    resistor: 10kOhm
    reference_voltage: 5
    id: resistance_sensor_3
  - platform: ntc
    sensor: resistance_sensor_3
    name: "Hot water reserve"
    id: water_reserve_temp
    calibration:
       - 10.0kOhm -> 25°C
       - 5.76kOhm -> 37.9°C
       - 15.98kOhm -> 14.1°C
    filters:
      - sliding_window_moving_average:
          window_size: 6
          send_every: 2

  - platform: template
    name: "Heating Water Delta Temp"
    lambda: |-
        return id(heating_outgress_temp).state - id(heating_ingress_temp).state;
    update_interval: 10s
    device_class: temperature
    unit_of_measurement: C

# Four relay outputs, exposed as switches in Home Assistant
switch:
  - platform: gpio
    pin: GPIO16
    name: Relay1
    id: relay1
  - platform: gpio
    pin: GPIO14
    name: Relay2
    id: relay2
  - platform: gpio
    pin: GPIO12
    name: Relay3
    id: relay3
  - platform: gpio
    pin: GPIO13
    name: Relay4
    id: relay4
  - platform: gpio
    pin: GPIO15
    name: Relay5
    id: relay5
  - platform: gpio
    pin: GPIO00
    name: Relay6
    id: relay6
  - platform: gpio
    pin: GPIO04
    name: Relay7
    id: relay7
  - platform: gpio
    pin: GPIO05
    name: "Hot Water Pump"
    id: relay8
  - platform: template
    id: "hot_water_circulation"
    name: "Hot Water Circulation"
    icon: "mdi:pump"
    lambda: |-
      return id(is_hot_water_circulation_on);
    turn_on_action:
      - lambda: |-
           id(is_hot_water_circulation_on) = true;
      - switch.turn_on: relay8
    turn_off_action:
      - lambda: |-
           id(is_hot_water_circulation_on) = false;
