esphome:
  name: pince_mester
  platform: ESP32
  board: nodemcu-32s
  on_boot:
    priority: -100
    then:
      - switch.turn_on: led_wifi

wifi:
  fast_connect: true
  power_save_mode: none  
  output_power: 20db  
  ssid: !secret wifi_ssid
  password: !secret wifi_password


script:
    - id: stop_all 
      then: 
        - switch.turn_off: relay_hatul
        - switch.turn_off: relay_elol
        - switch.turn_off: relay_grup
        - switch.turn_off: relay_cserep
        - switch.turn_off: relay_kert
    - id: start_watter 
      then:  
        - if:
            condition:
               - switch.is_on: use_tank
            then:
               - switch.turn_off: relay_vezetek
               - switch.turn_on: relay_pompa
            else: 
               - switch.turn_off: relay_pompa
               - switch.turn_on: relay_vezetek
          
# Enable logging
logger:

# Enable Home Assistant API
api:

status_led:
  pin: GPIO02

ota:
  safe_mode: True
  password: !secret ota_password

switch:
  - id: use_tank
    icon: "mdi:water-pump"
    name: "Van viz a tartalyban?" 
    platform: gpio
    pin: 
      number: GPIO4
  - id: led_wifi
    platform: gpio
    pin: 
      number: GPIO0
    restore_mode: ALWAYS_OFF    
  - id: relay_hatul
    platform: gpio
    pin: 
      number: GPIO23
      inverted: true   
    restore_mode: ALWAYS_OFF    
  - id: relay_elol
    platform: gpio
    pin: 
      number: GPIO22
      inverted: true   
    restore_mode: ALWAYS_OFF    
  - id: relay_grup
    platform: gpio
    pin: 
      number: GPIO21
      inverted: true   
    restore_mode: ALWAYS_OFF    
  - id: relay_cserep
    platform: gpio
    pin: 
      number: GPIO19
      inverted: true   
    restore_mode: ALWAYS_OFF    
  - id: relay_kert
    platform: gpio
    pin: 
      number: GPIO18
      inverted: true   
    restore_mode: ALWAYS_OFF    
  - id: relay_pompa
    name: "Pompa"
    icon: "mdi:water-pump"
    platform: gpio
    pin: 
      number: GPIO5
      inverted: true   
    restore_mode: ALWAYS_OFF    
  - id: relay_vezetek
    platform: gpio
    pin: 
      number: GPIO17
      inverted: true   
    restore_mode: ALWAYS_OFF    
  - id: relay_ajto
    name: "pince ajto"
    platform: gpio
    icon: "mdi:lock" 
    pin: 
      number: GPIO16
      inverted: true   
  - id: circuit_1
    name: "fu ontozo elol"
    platform: gpio
    icon: "mdi:sprinkler-variant"  
    pin: 
      number: GPIO13
    restore_mode: ALWAYS_OFF 
    interlock: 
      - circuit_2  
      - circuit_3  
      - circuit_4
      - circuit_5
    on_turn_on:    
      - script.execute: stop_all
      - script.execute: start_watter
      - switch.turn_on: relay_elol
      - delay: 30min
      - switch.turn_off: relay_elol
      - switch.turn_off: circuit_1
    on_turn_off:
      - switch.turn_off: relay_elol
  - id: circuit_2
    name: "fu ontozo hatul"
    icon: "mdi:sprinkler-variant"  
    platform: gpio
    pin: 
      number: GPIO15
    restore_mode: ALWAYS_OFF    
    interlock: 
      - circuit_1  
      - circuit_3  
      - circuit_4
      - circuit_5  
    on_turn_on:    
      - script.execute: stop_all
      - script.execute: start_watter
      - switch.turn_on: relay_hatul
      - delay: 30min 
      - switch.turn_off: relay_hatul
      - switch.turn_off: circuit_2
    on_turn_off:
      - switch.turn_off: relay_hatul
  - id: circuit_3
    name: "Grup csepi"
    icon: "mdi:watering-can"  
    platform: gpio
    pin: 
      number: GPIO14
    restore_mode: ALWAYS_OFF    
    interlock: 
      - circuit_2  
      - circuit_1  
      - circuit_4
      - circuit_5  
    on_turn_on:    
      - script.execute: stop_all
      - script.execute: start_watter
      - switch.turn_on: relay_grup
      - delay: 60min  
      - switch.turn_off: relay_grup
      - switch.turn_off: circuit_3
    on_turn_off:
      - switch.turn_off: relay_grup
  - id: circuit_4
    name: "Cherep csepi"
    icon: "mdi:watering-can"  
    platform: gpio
    pin: 
      number: GPIO12
    restore_mode: ALWAYS_OFF    
    interlock: 
      - circuit_2  
      - circuit_3  
      - circuit_1
      - circuit_5  
    on_turn_on:    
      - script.execute: stop_all
      - script.execute: start_watter
      - switch.turn_on: relay_cserep
      - delay: 30min  
      - switch.turn_off: relay_cserep
      - switch.turn_off: circuit_4
    on_turn_off:
      - switch.turn_off: relay_cserep
  - id: circuit_5
    name: "Kert ontozo"
    icon: "mdi:watering-can"  
    platform: gpio
    pin: 
      number: GPIO27
    restore_mode: ALWAYS_OFF    
    interlock: 
      - circuit_2  
      - circuit_3  
      - circuit_4
      - circuit_1  
    on_turn_on:    
      - script.execute: stop_all
      - script.execute: start_watter
      - switch.turn_on: relay_kert
      - delay: 60min 
      - switch.turn_off: relay_kert
      - switch.turn_off: circuit_5
    on_turn_off:
      - switch.turn_off: relay_kert

sensor:
  - platform: wifi_signal
    name: "WiFi Signal Pince"
    icon: "mdi:wifi"
    update_interval: 60s    
  # First Cable terminal ( from esb USB port)     
  - platform: adc
    pin: GPIO34
    icon: "mdi:battery-medium"
    attenuation: 6db  
    name: "Water Tank Level" 
    update_interval: 2s  
    unit_of_measurement: "cm"
    accuracy_decimals: 0
    filters: 
      - sliding_window_moving_average:
          window_size: 60
          send_every: 20            
            #- median:
            #window_size: 7
            #send_every: 4
            #send_first_at: 3      
      - calibrate_linear:
          - 0.538 -> 0
          - 0.620 -> 20
          - 0.703 -> 40
          - 0.812 -> 60
          - 0.902 -> 80
          - 0.998 -> 00
          - 1.240 -> 150
          - 1.485 -> 200
    on_value_range:
      #- above: 100
      #  then:
      #    - switch.turn_on: use_tank
      - below: 70
        then:
          - switch.turn_off: use_tank
          - switch.turn_off: relay_pompa
          - script.execute:  stop_all
  - platform: dht
    pin: GPIO32
    temperature:
      name: "Pince Temperature"
    humidity:
      name: "Pince Humidity"
    model: AM2302
    update_interval: 300s    
