esphome:
  name: pince_mester
  platform: ESP32
  board: nodemcu-32s
  on_boot:
      - switch.turn_off: relay_1
      - switch.turn_off: relay_2
      - switch.turn_off: relay_3
      - switch.turn_off: relay_4
      - switch.turn_off: relay_5
      - switch.turn_off: relay_6
      - switch.turn_off: relay_7
      - switch.turn_off: relay_8
      - switch.turn_on: led_1
      - delay: 2s  
      - switch.turn_off: led_1
      - delay: 1s  

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password


# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  safe_mode: True
  password: !secret ota_password

binary_sensor:
  - platform: gpio
    pin: 
      number: GPIO21
      mode: INPUT_PULLUP
    id: button_1
    on_press:
      then:
        - switch.toggle: led_1
        - delay: 2s  
        - switch.toggle: led_1
#        - delay: 500ms  
#        - switch.toggle: relay_1
#        - delay: 500ms  
#        - switch.toggle: relay_2
#        - delay: 500ms  
#        - switch.toggle: relay_3
#        - delay: 500ms  
#        - switch.toggle: relay_4
#        - delay: 500ms  
#        - switch.toggle: relay_5
#        - delay: 500ms  
#        - switch.toggle: relay_6
#        - delay: 500ms  
#        - switch.toggle: relay_7
#        - delay: 500ms  
#        - switch.toggle: relay_8

switch:
  - id: led_1
    platform: gpio
    pin: 
      number: GPIO13
  - id: relay_1
    platform: gpio
    pin: 
      number: GPIO12
      inverted: true   
    restore_mode: RESTORE_DEFAULT_OFF    
  - id: relay_2
    platform: gpio
    pin: 
      number: GPIO14
      inverted: true   
    restore_mode: RESTORE_DEFAULT_OFF    
  - id: relay_3
    platform: gpio
    pin: 
      number: GPIO27
      inverted: true   
    restore_mode: RESTORE_DEFAULT_OFF    
  - id: relay_4
    platform: gpio
    pin: 
      number: GPIO26
      inverted: true   
    restore_mode: RESTORE_DEFAULT_OFF    
  - id: relay_5
    platform: gpio
    pin: 
      number: GPIO25
      inverted: true   
    restore_mode: RESTORE_DEFAULT_OFF    
  - id: relay_6
    platform: gpio
    pin: 
      number: GPIO33
      inverted: true   
    restore_mode: RESTORE_DEFAULT_OFF    
  - id: relay_7
    platform: gpio
    pin: 
      number: GPIO32
      inverted: true   
    restore_mode: RESTORE_DEFAULT_OFF    
  - id: relay_8
    platform: gpio
    pin: 
      number: GPIO22
      inverted: true   
    restore_mode: RESTORE_DEFAULT_OFF    

sensor:
  - platform: wifi_signal
    name: "WiFi Signal Kucko"
    update_interval: 60s    
