esphome:
  name: kucko_mester  
  platform: ESP8266  
  board: esp01_1m
  on_boot:
    priority: -100
    then:
      light.turn_on:
        id: status_led

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

api:

logger:
  baud_rate: 0

uart:
  rx_pin: RX
  baud_rate: 4800

binary_sensor:
  - platform: gpio
    on_press:
      then:
        - cover.template.publish:
            id: gate
            state: OPEN  
            current_operation: OPENING  
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: "Open Gate"
  - platform: gpio
    on_press:
      then:
        - switch.toggle: button_2
    pin:
      number: GPIO9
      mode: INPUT_PULLUP
      inverted: True
    name: "Open Gate Pedestrian"
  - platform: gpio
    on_press:
      then:
        - cover.template.publish:
            id: gate
            state: CLOSED
            current_operation: CLOSING
    pin:
      number: GPIO10
      mode: INPUT_PULLUP
      inverted: True
    name: "Close Gate"
  - platform: gpio
    on_press:
      then:
        - switch.toggle: button_4
    pin:
      number: GPIO14
      mode: INPUT_PULLUP
      inverted: True
    name: "Open Door"
  - platform: status
    name: "Kucko Mester Status"

switch:
  - platform: gpio
    id: button_1
    name: "Open Gate"
    pin: GPIO12
  - platform: gpio
    id: button_2
    name: "Open Gate Pedestrian"
    pin: GPIO5
  - platform: gpio
    id: button_3
    name: "Close Gate"
    pin: GPIO4
  - platform: gpio
    id: button_4
    name: "Open Door"
    pin: GPIO15

output:
  - platform: esp8266_pwm
    id: blue_led
    pin: GPIO13
    inverted: True

light:
  - platform: monochromatic
    id: status_led
    name: "Sonoff 4CH Blue LED"
    output: blue_led

cover: 
  - platform: template
    id: "gate"
    name: "Gate"
    open_action:
      # Cancel any previous action
      - switch.turn_off: button_3
      # Turn the OPEN switch on briefly
      - switch.turn_on: button_1
      - delay: 0.1s
      - switch.turn_off: button_1
    close_action:
      - switch.turn_off: button_1
      - switch.turn_off: button_2
      - switch.turn_on: button_3
      - delay: 0.1s
      - switch.turn_off: button_3
    optimistic: true
    assumed_state: true    

ota:
  safe_mode: True
  password: !secret ota_password

web_server:
  port: 80    
