esphome:
  name: kucko_mester  
  platform: ESP8266  
  board: esp01_1m
  on_boot:
    priority: -100
    then:
      light.turn_on:
        id: status_led

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

api:

logger:
  baud_rate: 0

uart:
  rx_pin: RX
  baud_rate: 4800

binary_sensor:
  - platform: gpio
    id: press_1
    on_press:
      then:
        - switch.toggle: open_gate
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
  - platform: gpio
    id: press_2
    on_press:
      then:
        - switch.toggle: open_pedestrian
    pin:
      number: GPIO9
      mode: INPUT_PULLUP
      inverted: True
  - platform: gpio
    id: press_3
    on_press:
      then:
        - switch.toggle: gate_close
    pin:
      number: GPIO10
      mode: INPUT_PULLUP
      inverted: True
  - platform: gpio
    id: press_4
    on_press:
      then:
        - switch.toggle: button_4
    pin:
      number: GPIO14
      mode: INPUT_PULLUP
      inverted: True
  - platform: status
    name: "Kucko Mester Status"

switch:
  - platform: gpio
    id: relay_1
    pin: GPIO12
    restore_mode: ALWAYS_OFF
    interlock: [relay_2, relay_3]  
  - platform: template
    id: open_gate
    name: "Gate Open"
    icon: "mdi:gate"
    turn_on_action:
      - switch.turn_on: relay_1
      - delay: 300ms
      - switch.turn_off: relay_1   
  - platform: gpio
    id: relay_2
    pin: GPIO5
    restore_mode: ALWAYS_OFF
    interlock: [relay_1, relay_3]  
  - platform: template
    id: open_pedestrian
    name: "Gate Pedestrian"
    icon: "mdi:gate"
    turn_on_action:
      - switch.turn_on: relay_2
      - delay: 300ms
      - switch.turn_off: relay_2
  - platform: gpio
    id: relay_3
    pin: GPIO4
    restore_mode: ALWAYS_OFF
    interlock: [relay_1, relay_2]  
  - platform: template
    id: gate_close
    name: "Gate Close"
    icon: "mdi:gate"
    turn_on_action:
      - switch.turn_on: relay_3
      - delay: 300ms
      - switch.turn_off: relay_3
  - platform: gpio
    id: button_4
    name: "Kucko ajto"
    icon: "mdi:lock" 
    pin: GPIO15

output:
  - platform: esp8266_pwm
    id: blue_led
    pin: GPIO13
    inverted: True

light:
  - platform: monochromatic
    id: status_led
    name: "Sonoff 4CH Blue LED"
    output: blue_led

ota:
  safe_mode: True
  password: !secret ota_password

sensor:
  - platform: wifi_signal
    name: "WiFi Signal Kucko"
    update_interval: 60s    
