esphome:
  name: fozomester
  on_boot:
    priority: -100
    then:
      light.turn_on:
         id: status_led

esp8266:
  board: esp8285

logger:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  reboot_timeout: 10h
api:

ota:
  safe_mode: True
  password: !secret ota_password

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode:
        input: true
        pullup: true
      inverted: true
    id: button_1
    on_press:
      then:
        - switch.turn_on: r3
        - switch.turn_on: r1
        - switch.turn_off: r2
  
  - platform: gpio
    pin:
      number: GPIO9
      mode:
        input: true
        pullup: true
      inverted: true
    id: button_2
    on_press:
      then:
        - switch.turn_on: r3
        - switch.turn_off: r1
        - switch.turn_on: r2
        - delay: 10s
        - switch.turn_on: r1
        - switch.turn_off: r2
  
  - platform: gpio
    pin:
      number: GPIO10
      mode:
        input: true
        pullup: true
      inverted: true
    id: button_3
    on_press:
      then:
        - switch.toggle: r3
  
  - platform: gpio
    pin:
      number: GPIO14
      mode:
        input: true
        pullup: true
      inverted: true
    id: button_4
  
  - platform: status
    name: "Fozo Mester Status"


switch:
  - platform: gpio
    pin: GPIO12
    id: r1
  - platform: gpio
    pin: GPIO5
    id: r2
  - platform: gpio
    name: "R3"
    pin: GPIO4
    id: r3
  - platform: gpio
    name: "R4"
    pin: GPIO15
    id: r4 

output:
  # Register the blue LED as a dimmable output ....
  - platform: esp8266_pwm
    id: blue_led
    pin: GPIO13
    inverted: true

light:
  # ... and then make a light out of it.
  - platform: monochromatic
    output: blue_led
    id: status_led

sensor:
  - platform: wifi_signal
    name: "WiFi Signal Ontozo Mester"
    update_interval: 60s   

