esphome:
  name: ontozo_mester
  on_boot:
    priority: -100
    then:
      light.turn_on:
         id: status_led

esp8266:
  board: esp8285

logger:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

api:

ota:
  safe_mode: True
  password: !secret ota_password

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode:
        input: true
        pullup: true
      inverted: true
    id: button_1
  
  - platform: gpio
    pin:
      number: GPIO9
      mode:
        input: true
        pullup: true
      inverted: true
    id: buttonm_2
  
  - platform: gpio
    pin:
      number: GPIO10
      mode:
        input: true
        pullup: true
      inverted: true
    id: button_3
  
  - platform: gpio
    pin:
      number: GPIO14
      mode:
        input: true
        pullup: true
      inverted: true
    id: button_4
  
  - platform: status
    name: "Ontozo Mester Status"

switch:
  - platform: gpio
    id: fu_hatul
    name: "Ontozes Fu hatul"
    pin: GPIO12
    interlock:
      - fu_elol
      - gruppok
      - cserep_csepi
      - vetemenyes
  - platform: gpio
    id: fu_elol
    name: "Ontozes Fu elol"
    pin: GPIO5
    interlock:
      - fu_hatul
      - gruppok
      - cserep_csepi
      - vetemenyes
  - platform: gpio
    id: gruppok
    name: "Ontozes Gruppok"
    pin: GPIO4
    interlock:
      - fu_hatul
      - fu_elol
      - cserep_csepi
      - vetemenyes
  - platform: gpio
    id: cserep_csepi
    name: "Ontozes Cserep Csepi"
    interlock:
      - fu_hatul
      - fu_elol
      - gruppok
      - vetemenyes
    pin: GPIO15
  - platform: gpio
    name: "EXTRA 2"
    pin: GPIO3
    inverted: true
  - platform: gpio
    id: vetemenyes
    interlock:
      - fu_hatul
      - fu_elol
      - gruppok
      - cserep_csepi
    name: "Ontozes Vetemenyes"
    pin: GPIO1
    inverted: true
  - platform: gpio
    name: "EXTRA 3"
    pin: GPIO2
    inverted: true

output:
  # Register the blue LED as a dimmable output ....
  - platform: esp8266_pwm
    id: blue_led
    pin: GPIO13
    inverted: true

light:
  # ... and then make a light out of it.
  - platform: monochromatic
    output: blue_led
    id: status_led

sensor:
  - platform: wifi_signal
    name: "WiFi Signal Ontozo Mester"
    update_interval: 60s    
