esphome:
  name: pia_mester
  platform: ESP32
  board: esp32dev

logger:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  power_save_mode: none  

api:

#web_server:
#   port: 80

ota:
  safe_mode: True
  password: !secret ota_password
 
i2c:
  - id: bus_a
    sda: 21
    scl: 22
    scan: true

ads1115:
  - address: 0x48
    continuous_mode: true

globals:
   - id: water_runtime_min
     type: int
     restore_value: no
     initial_value: '0'

sensor:
 - platform: dht
   pin: GPIO4
   temperature:
     name: "Pince Temperature"
   humidity:
     name: "Pince Humidity"
   model: AM2302
   update_interval: 30s
# - platform: ads1115
#   multiplexer: 'A0_GND'
#   id: voltage_sensor_0
#   name: "Viz Tartaly Szint"
#   gain: 6.144
#   update_interval: 3s
#   accuracy_decimals: 1
# - platform: ads1115
#   multiplexer: 'A1_GND'
#   id: voltage_sensor_1
#   # TODO: AC to DC , Ez tulfolyo pompa lesz a proba utan
#   name: "Urito pompa aram eroseg"
#   gain: 1.024
#   update_interval: 3s
#   filters:
#      - multiply: -1
#      - offset: -1
#   accuracy_decimals:
 - platform: template
   id: water_runtime
   unit_of_measurement: "m"
   accuracy_decimals: 0
   name: "Time the watter was running"
   icon: "mdi:watering-can"
   update_interval: 1min
   lambda: |-
     if (id(water_flow).state) id(water_runtime_min)+=1; return id(water_runtime_min);
   on_value_range:
     above: 45
     then:
       - switch.turn_off: water_flow
  
# 8 relay outputs, exposed as switches in Home Assistant
switch:
  - platform: gpio
    pin: GPIO32
    name: "Vetemenyes Csepi"
    id: ontoz_vetemenyes
    interlock:
      - ontoz_cserep
      - ontoz_grup 
      - ontoz_fu_elol
      - ontoz_fu_hatul
    on_turn_on: 
       - switch.turn_on: water_flow
    on_turn_off:
       - switch.turn_off: water_flow
  - platform: gpio
    pin: GPIO33
    name: "Cherep Csepi"
    interlock:
      - ontoz_vetemenyes
      - ontoz_grup 
      - ontoz_fu_elol
      - ontoz_fu_hatul
    id: ontoz_cserep
    on_turn_on: 
       - switch.turn_on: water_flow
    on_turn_off:
       - switch.turn_off: water_flow
  - platform: gpio
    pin: GPIO25
    name: "Grupp csepi"
    id: ontoz_grup
    interlock:
      - ontoz_vetemenyes
      - ontoz_cserep
      - ontoz_fu_elol
      - ontoz_fu_hatul
    on_turn_on: 
       - switch.turn_on: water_flow
    on_turn_off:
       - switch.turn_off: water_flow
  - platform: gpio
    pin: GPIO26
    name: "Fu elol"
    id: ontoz_fu_elol
    interlock:
      - ontoz_vetemenyes
      - ontoz_cserep
      - ontoz_grup 
      - ontoz_fu_hatul
    on_turn_on: 
       - switch.turn_on: water_flow
    on_turn_off:
       - switch.turn_off: water_flow
  - platform: gpio
    pin: GPIO27
    name: "Fu hatul"
    id: ontoz_fu_hatul
    interlock:
      - ontoz_vetemenyes
      - ontoz_cserep
      - ontoz_grup 
      - ontoz_fu_elol
    on_turn_on: 
       - switch.turn_on: water_flow
    on_turn_off:
       - switch.turn_off: water_flow
  - platform: gpio
    pin: GPIO14
    name: "Vezetek Viz Inditas"
    id: ontozes_vezetek
    interlock:
      - ontozes_pompa
  - platform: gpio
    pin: GPIO12
    name: "Pompa Viz Inditas"
    id: ontozes_pompa
    interlock:
       - ontozes_vezetek
  - platform: gpio
    pin: GPIO13
    name: "Relay8 nincs hasznalatban"
    id: relay8
  - platform: gpio
    pin: GPIO18
    name: "Urito Pompa"
    id: relayA1
    inverted: true 
  - platform: gpio
    pin: GPIO19
    name: "Pince Ajto"
    id: relayA2
    inverted: true 
  - platform: template
    id: use_tank
    optimistic: true 
    icon: "mdi:water-pump"
    name: "Van viz a tartalyban?"
  - platform: template
    id: water_flow
    icon: "mdi:water-pump"
    name: "Viz inditasa"
    optimistic: true
    turn_on_action:
       then:  
          - if:
               condition:
                 - switch.is_on: use_tank
               then:
                 - switch.turn_on: ontozes_pompa
               else:
                 - switch.turn_on: ontozes_vezetek
    turn_off_action:
          - switch.turn_off: ontozes_pompa
          - switch.turn_off: ontozes_vezetek
          - switch.turn_off: water_flow
